site_name: Cy4's Forge Wiki
site_url: https://cy4mods.me/wiki/
repo_url: https://github.com/Cy4Shot/ForgeWiki/
repo_name: Cy4Shot/ForgeWiki
nav:
  - Home:
      - index.md
      - Landing Page: index.md
      - Contributing:
          - Contribution Tutorial: contributing/tutorial.md
          - Contribution Guidelines: contributing/guidelines.md
      - Generators:
          - Mappings: mappings.md
      - Community: community/index.md
      - Credits: credits.md
  - 1.19.x:
      - 1.19.x/index.md
      - Home: 1.19.x/index.md
      - Setup:
          - 1.19.x/setup/index.md
          - Installation:
              - Installing Java: 1.19.x/setup/installation/java.md
              - Installing An IDE: 1.19.x/setup/installation/ide.md
              - Downloading Forge: 1.19.x/setup/installation/forge.md
          - Configuration:
              - Buildscript: 1.19.x/setup/configuration/buildscript.md
              - Gradlew Commands: 1.19.x/setup/configuration/gradlew.md
              - Mod File: 1.19.x/setup/configuration/mod-file.md
              - Main Class: 1.19.x/setup/configuration/main-class.md
      - Tools:
          - 1.19.x/tools/index.md
          - Mixin: 1.19.x/tools/mixin.md
          - Access Transformers: 1.19.x/tools/at.md
  - 1.18.x:
      - 1.18.x/index.md
      - Home: 1.18.x/index.md
      - Setup:
          - 1.18.x/setup/index.md
          - Installation:
              - Installing Java: 1.18.x/setup/installation/java.md
              - Installing An IDE: 1.18.x/setup/installation/ide.md
              - Downloading Forge: 1.18.x/setup/installation/forge.md
          - Configuration:
              - Buildscript: 1.18.x/setup/configuration/buildscript.md
              - Gradlew Commands: 1.18.x/setup/configuration/gradlew.md
              - Mod File: 1.18.x/setup/configuration/mod-file.md
              - Main Class: 1.18.x/setup/configuration/main-class.md
      - Blocks and Items:
          - 1.18.x/basic-content/index.md
          - Registries: 1.18.x/basic-content/registries.md
          - Items: 1.18.x/basic-content/items.md
          - Blocks: 1.18.x/basic-content/blocks.md
          - Loot-Tables: 1.18.x/basic-content/loot-tables.md
      - Tools:
          - 1.18.x/tools/index.md
          - Mixin: 1.18.x/tools/mixin.md

          - Access Transformers: 1.18.x/tools/at.md
plugins:
  - search
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - md_in_html
extra_javascript:
  - js/sort.js
  - js/grid.js
  - js/case.js
  - js/mathjax.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/axios/dist/axios.min.js
  - js/mappings.js
  - https://unpkg.com/nprogress@0.2.0/nprogress.js
extra_css:
  - css/grid.css
  - css/extra.css
  - https://unpkg.com/nprogress@0.2.0/nprogress.css
theme:
  name: material
  logo: ./assets/logo.png
  favicon: ./assets/logo.png
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
    - content.tooltips
    - content.code.copy
    - content.code.annotate 
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  generator: false