site_name: Cy4's Forge Wiki
site_url: https://cy4mods.me/wiki/
nav:
  - Home:
      - index.md
      - Contributing:
          - Contribution Tutorial: Contributing/tutorial.md
          - Contribution Guidelines: Contributing/guidelines.md
      - Community:
          - Community/index.md
      - Credits: credits.md
  - 1.19.x:
      - 1.19.x/index.md
      - Setup:
          - 1.19.x/Setup/index.md
          - Installation:
              - Installing Java: 1.19.x/Setup/Installation/java.md
              - Installing An IDE: 1.19.x/Setup/Installation/ide.md
              - Downloading Forge: 1.19.x/Setup/Installation/forge.md
plugins:
  - search
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - css/extra.css
theme:
  name: material
  logo: ./assets/logo.png
  favicon: ./assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - content.tooltips
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
